import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import {
  Modal,
	ModalProvider,
  useModal,
  ModalTransition,
} from '../components/react-simple-modal'
import {
	Popup,
	PopupProps
} from '../components/popup-menu'
import styled from 'styled-components'
import { theme } from '../theme'
import NextShift from '../components/NextShift'
import Calendar from '../components/Calendar'
import 'react-simple-hook-modal/dist/styles.css'

const ModalContent = ({ transition, onCloseClicked }) => {
  const { isModalOpen, openModal, closeModal } = useModal();
  const [toggle, setToggle] = React.useState(false);

  return (
	<>
	<div class="flex mx-auto">
	<div class="flex w-full border-b border-gray-900">
		<button class="flex items-center justify-center px-4">
			<svg class="w-6 h-6 text-gray-600" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
				<path d="M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z">
				</path>
			</svg>
		</button>
		<input type="text" class="px-4 py-5 w-full bg-gray-900" placeholder="Search..."/>
		<Popup 
			trigger={<button class="flex items-center justify-center px-4">
								<svg class="w-6 h-6 text-gray-600" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
									<path d="M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z"></path>
								</svg>
							</button>}
			position={['left top', 'left top']}
			on="click"
			mouseLeaveDelay={300}
			mouseEnterDelay={0}
			contentStyle={{ padding: '0px', border: 'none' }}
			onClose={() => console.log('close ')}
			onOpen={() => console.log('open ')}
			arrow={false}>
			<div className="menu">
				<div className="menu-item">All Notifications</div>
				<div className="menu-item">Critical Notifications</div>
				<div className="menu-item">Urgent Notifications</div>
				<div className="menu-item">Information Priority</div>
				<div className="menu-item">General Priority</div>
				<div className="menu-item">Unread Notification</div>
				<div className="menu-item">Read/Archived Notifications</div>
			</div>
		</Popup>
	</div>
	</div>
	<div class="font-sans flex items-center justify-center bg-blue-darker w-full">
		<div class="overflow-hidden bg-gray-600 max-w w-full shadow-lg leading-normal">
			<a class="cursor-pointer flex p-4">
				<div class="w-8 h-10 text-center py-1">
					<p class="text-5xl p-0 text-green-dark">&bull;</p>
				</div>
				<div class="w-5 h-10 py-3 px-6 w-full h-full">
					<p class="font-bold text-lg mb-1 text-white group-hover:text-white">Create from scratch</p>
					<p class="text-grey-darker mb-2 group-hover:text-white">Create a repository without any source code</p>
					<p class="text-grey-darker">a day ago</p>
				</div>
			</a>
			{/*<a href="#" class="block group hover:bg-blue p-4">
				<p class="font-bold text-lg mb-1 text-black group-hover:text-white">Fork</p>
				<p class="text-grey-darker mb-2 group-hover:text-white">Start a project base on the source of an existing one.</p>
			</a>*/}
		</div>
	</div>
	{toggle ? (
		<div className="mt-4">
			{[...Array(30)].map((e, i) => (
				<p key={i} className="mb-2">
					Are you using react-simple-hook-modal yet?
				</p>
			))}
		</div>
	) : null}
	</>
  );
};

const HomeWrapper = styled.div`
	align-items: center;
	background-color: ${theme.colors.backgroundDarker};
	display: flex;
	flex-direction: column;
	justify-content: center;
	font-family: 'Arial', sans-serif;
`
const HomeMain = styled.main`
  padding: 3rem 0;
  flex: 1;
  display: grid;
	grid-template-rows: 1fr 1.5fr;
	margin-top: 6.5rem;
  row-gap: 3rem;
	width: 100%;
`
const ShiftsAvailability = styled.div`
	display: flex;
`
function HomePage() {
	const scheduledShifts = [new Date(), new Date(), new Date()]
  const { isModalOpen, openModal, closeModal } = useModal()
  console.log('Home update ', isModalOpen)
  return (
    <HomeWrapper>
      	<Head>
        	<title>Timecard</title>
        	<meta name="description" content="Generated by create next app" />
        	<link rel="icon" href="/favicon.ico" />
      	</Head>
				<AppHeader openModal={openModal} />
      	<HomeMain>
					<NextShift />
        	<Calendar />
      	</HomeMain>
				<AppFooter />
      	<Modal
        	id="1"
        	isOpen={isModalOpen}
        	onBackdropClick={closeModal}
        	transition={ModalTransition.BOTTOM_UP}
					transformDistanceOffsetX={0}
					transformDistanceOffsetY={134.4}
      	>
        	<ModalContent transition={ModalTransition.BOTTOM_UP} onCloseClicked={closeModal} />
      	</Modal>
    </HomeWrapper>
  )
}

export default function Home() {
  return (
    <ModalProvider>
      <HomePage />
    </ModalProvider>
  )
}

const HomeFooter = styled.footer`
  display: flex;
  flex-direction: column;
  grid-area: footer;
  background-color: #808080;
  flex: 1;
  width: 100%;
  border-top: 1px solid #eaeaea;
  display: flex;
  justify-content: center;
  align-items: center;
  min-width: 100%;
`
const HomeFooterTopRow = styled.div`
  background-color: ${theme.colors.backgroundLight};
  display: flex;
  flex: 1;
  min-height: 3.2rem;
  min-width: 100%;
  position: fixed;
  bottom: 72px;
  right: 0;
`
const HomeFooterBottomRow = styled.div`
  display: flex;
  min-width: 100%;
  z-index: 9999;
  position: fixed;
  bottom: 0;
  right: 0;
`
export function AppFooter() {
  return (
      <HomeFooter>
        <HomeFooterTopRow>
          <HomeFooterTopRowSection
            alt={'LayersIcon'}
            className={'MenuRightChild'}
            imageSrc={'/calendaricon.svg'}
            label={'Shifts'}
            path={'shifts'}
          />
          <HomeFooterTopRowSection
            alt={'LayersIcon'}
            className={'FooterTopRowClockImage'}
            imageSrc={'/clockicon.svg'}
            label={'Availability'}
            path={'availability'}
          />
        </HomeFooterTopRow>
        <HomeFooterBottomRow>
          <HomeFooterBottomRowSection
              imageSrc={'/homeicon.svg'}
              alt={'HomeIcon'}
              className={'FooterBottomRowImage'}
              label={'Home'}
              path={'home'}
          />
          <HomeFooterBottomRowSection
              imageSrc={'/calendaricon.svg'}
              alt={'CalendarIcon'}
              className={'FooterBottomRowImage'}
              label={'Self Service'}
              path={'selfservice'}
          />
        </HomeFooterBottomRow>
      </HomeFooter>
  )
}

const HomeFooterBottomRowSectionContainer = styled.div`
  align-items: center;
  background-color: ${theme.colors.backgroundLight};
  color: ${theme.colors.textLight};
  display: flex;
  flex-direction: column;
  flex: 1;
  justify-content: center;
  padding-left: 1rem;
  height: 4.5rem;
  background-color: ${theme.colors.green};
`
const HomeFooterBottomRowSectionSpan = styled.span`
  display: block;
  font-weight: 500;
  font-size: 0.8rem;
  margin-top: 2px;
  margin-bottom: 1rem;
`
function HomeFooterBottomRowSection({ alt, className, imageSrc, label, path }) {
  return (
    <Link href={path}>
      <HomeFooterBottomRowSectionContainer>
        <ImageContainer
          color={theme.colors.greenFade}
          imageSrc={imageSrc}
          alt={alt}
          className={className}
          height={36}
          width={36}
          margin={'20px 0 0 0'}
        />
        <HomeFooterBottomRowSectionSpan>{label}</HomeFooterBottomRowSectionSpan>
      </HomeFooterBottomRowSectionContainer>
    </Link>
  )
}

const HomeFooterTopRowSectionContainer = styled.div`
  align-items: center;
  background-color: ${theme.colors.backgroundLight};
  color: ${theme.colors.textLight};
  cursor: pointer;
  display: flex;
  flex: 1;
  padding-left: 1rem;
  max-width: 12rem;
`
const HomeFooterTopRowSectionSpan = styled.span`
  display: block;
  font-weight: 900;
  font-size: 1.3rem;
`
function HomeFooterTopRowSection({ alt, className, imageSrc, label, path }) {
  return (
  	<Link href={path}>
    	<HomeFooterTopRowSectionContainer>
      	<ImageContainer
        	imageSrc={imageSrc}
        	className={className}
          alt={alt}
          margin={'0 20px 0 0'}
				/>
				<HomeFooterTopRowSectionSpan>{label}</HomeFooterTopRowSectionSpan>
			</HomeFooterTopRowSectionContainer>
		</Link>
  )
}

const HomeHeader = styled.header`
  position: fixed;
  top: 0;
  right: 0;
  width: 100%;
  min-height: 5rem;
  background-color: ${theme.colors.backgroundDarkest};
  display: grid;
  grid-template-columns: auto auto auto;
  grid-template-rows: auto;
  grid-template-areas:
    "headerGap header headerMenu"
    "headerLower headerLower headerLower";
`
const HomeHeaderTitleContainer = styled.div`
  grid-area: header;
  left: auto;
  right: auto;
  position: relative;
  display: flex;
  justify-content: center;
`
const HomeHeaderTitle = styled.div`
  color: #808080;
  font-size: 4rem;
`
const HomeHeaderTitleBold = styled.div`
  color: #ffffff;
  font-weight: 700;
  font-size: 4rem;
`
const HomeHeaderTitleMenuRight = styled.div`
  display: flex;
  grid-area: headerMenu;
  justify-content: flex-end;
  position: absolute;
  right: 0;
  margin-top: 1.2rem;
`
const HomeHeaderTitleLowerRow = styled.div`
  color: ${theme.colors.textLight};
  font-size: 1.6rem;
  grid-area: headerLower;
  display: flex;
  justify-content: center;
`
export function AppHeader({ openModal }) {
  return (
    <>
      <HomeHeader>
        <HomeHeaderTitleContainer>
          <HomeHeaderTitle>The</HomeHeaderTitle>
          <HomeHeaderTitleBold>Pantry</HomeHeaderTitleBold>
        </HomeHeaderTitleContainer>
        <HomeHeaderTitleMenuRight>
          <ImageContainer
            imageSrc={'/layersicon.svg'}
            className={'MenuRightChild'}
            alt={'LayersIcon'}
            margin={'0 1rem 0 0'}
          />
          <button
            className="p-3 text-white rounded"
            onClick={openModal}
          >
          <ImageContainer
            imageSrc={'/bellicon.svg'}
            className={'MenuRightChild'}
            alt={'BellIcon'}
            margin={'0 1rem 0 0'}
            onClick={openModal}
          />
					</button>
          <ImageContainer
            imageSrc={'/usericon.svg'}
            className={'MenuRightChild'}
            alt={'ProfileIcon'}
            margin={'0 1rem 0 0'}
          />
        </HomeHeaderTitleMenuRight>
        <HomeHeaderTitleLowerRow>{`Self Service`}</HomeHeaderTitleLowerRow>
      </HomeHeader>
    </>
  )
}

const ImageContainerDiv = styled.div`
	align-items: center;
	cursor: pointer;
	display: flex;
	justify-content: center;
	margin: ${props => props.margin};
	text-align: center;
`
export function ImageContainer({ color, imageSrc, className, alt, width=32, height=26, margin, onClick }) {
	return (
		<ImageContainerDiv
			margin={margin}
		>
    	<Image
				src={imageSrc}
				className={className}
				alt={alt}
				width={width}
				height={height}
				onClick={onClick}
			/>
		</ImageContainerDiv>
	)
}
