import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import NextShift from '../components/NextShift'
import Calendar from '../components/Calendar'
import Header from '../components/Header'

const HomeWrapper = styled.div`
  background-color: #1e2023;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`
const HomeMain = styled.main`
  padding: 3rem 0;
  flex: 1;
  display: grid;
	grid-template-rows: 1fr 1.5fr;
	margin-top: 3rem;
  row-gap: 3rem;
	width: 100%;
`
const HomeHeader = styled.header`
	position: fixed;
	top: 0;
	right: 0;
	width: 100%;
	min-height: 5rem;
	background-color: #000;
`
const HomeFooter = styled.footer`
	background-color: #808080;
  width: 100%;
  height: 100px;
  border-top: 1px solid #eaeaea;
  display: flex;
  justify-content: center;
  align-items: center;
	position: fixed;
	top: 0;
	right: 0;
	width: 100%;
`
const LogoSpan = styled.span`
  height: 1em;
  margin-left: 0.5rem;
`
const ShiftsAvailability = styled.div`
	display: flex;
`
const HomeSelfService = styled.div`
	background-color: green;
	display: flex;
`
const HomeHeaderTitle = styled.div``
const HomeHeaderTitleMenuRight = styled.div``
const HomeHeaderTitleLowerRow = styled.div``
export function AppHeader() {
	return (
		<HomeHeader>
			<HomeHeaderTitle></HomeHeaderTitle>
			<HomeHeaderTitleMenuRight></HomeHeaderTitleMenuRight>
			<HomeHeaderTitleLowerRow></HomeHeaderTitleLowerRow>
		</HomeHeader>
	)
}
export function AppFooter() {
	return (
      <HomeFooter>
				<ShiftsAvailability>
					
				</ShiftsAvailability>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <LogoSpan>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </LogoSpan>
        </a>
      </HomeFooter>
	)
}

export default function Home() {
	const scheduledShifts = [new Date(), new Date(), new Date()]
  return (
    <HomeWrapper>
      <Head>
        <title>Timecard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<AppHeader />
      <HomeMain>
				<NextShift />
        <Calendar scheduledShifts={scheduledShifts} />
      </HomeMain>
    </HomeWrapper>
  )
}

