import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styled from 'styled-components'
import { theme } from '../theme'
import NextShift from '../components/NextShift'
import Calendar from '../components/Calendar'
import { AppFooter, AppHeader } from './index'

const HomeWrapper = styled.div`
  align-items: center;
  background-color: ${theme.colors.backgroundDarker};
  display: flex;
  flex-direction: column;
  justify-content: center;
  font-family: 'Arial', sans-serif;
`
const HomeMain = styled.main`
  padding: 3rem 0;
  flex: 1;
  display: grid;
  grid-template-rows: 1fr 1.5fr;
  margin-top: 3rem;
  row-gap: 3rem;
  width: 100%;
`

export default function Shifts() {
  const scheduledShifts = [new Date(), new Date(), new Date()]
//  const [showOverlay, setShowOverlay] = React.useState(false)
  return (
    <HomeWrapper>
      <Head>
        <title>Timecard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader />
      <HomeMain>
        <NextShift />
        <Calendar />
      </HomeMain>
      <AppFooter />
    </HomeWrapper>
  )
}

